// <auto-generated />
using System;
using CommonLibrary.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace API_Purchase.Migrations
{
    [DbContext(typeof(PurchaseDBContext))]
    [Migration("20231216101643_PurchaseDetailChange")]
    partial class PurchaseDetailChange
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CommonLibrary.Models.Purchase", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<DateTime?>("purchaseDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("vendorId")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.ToTable("Purchases");
                });

            modelBuilder.Entity("CommonLibrary.Models.PurchaseDetail", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int>("itemId")
                        .HasColumnType("int");

                    b.Property<DateTime>("lastEditat")
                        .HasColumnType("datetime2");

                    b.Property<int>("purchaseId")
                        .HasColumnType("int");

                    b.Property<float>("qty")
                        .HasColumnType("real");

                    b.Property<float>("rate")
                        .HasColumnType("real");

                    b.HasKey("id");

                    b.HasIndex("purchaseId");

                    b.ToTable("PurchaseDetails");
                });

            modelBuilder.Entity("CommonLibrary.Models.PurchaseDetail", b =>
                {
                    b.HasOne("CommonLibrary.Models.Purchase", "Purchase")
                        .WithMany("PurchaseDetails")
                        .HasForeignKey("purchaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Purchase");
                });

            modelBuilder.Entity("CommonLibrary.Models.Purchase", b =>
                {
                    b.Navigation("PurchaseDetails");
                });
#pragma warning restore 612, 618
        }
    }
}
